<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE313V4.wsdl"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:apachesoap="http://xml.apache.org/xml-soap"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:IE313V4="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE313V4.wsdl"
    xmlns:IE313V4Ent="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE313V4Ent.xsd"
    xmlns:IE304V4Sal="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE304V4Sal.xsd"
    xmlns:IE305V4Sal="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE305V4Sal.xsd"
    xmlns:IE351V4Sal="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE351V4Sal.xsd"
    xmlns:IE917V4Sal="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE917V4Sal.xsd">
    <wsdl:documentation>Servicio que define el envio de una modificacion de una ENtry Sumary (ENS) en el sistema de informacion de aduanas.</wsdl:documentation>
    <wsdl:types>
        <schema elementFormDefault="qualified" targetNamespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE313V4.wsdl"
            xmlns="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE313V4Ent.xsd" schemaLocation="IE313V4Ent.xsd"/>
            <xsd:import namespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE304V4Sal.xsd" schemaLocation="IE304V4Sal.xsd"/>
            <xsd:import namespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE305V4Sal.xsd" schemaLocation="IE305V4Sal.xsd"/>
            <xsd:import namespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE351V4Sal.xsd" schemaLocation="IE351V4Sal.xsd"/>
            <xsd:import namespace="https://www2.agenciatributaria.gob.es/ADUA/internet/es/aeat/dit/adu/aden/enswsv4/IE917V4Sal.xsd" schemaLocation="IE917V4Sal.xsd"/>
            <xsd:complexType name="IE313V4SalType">
                <xsd:choice>
                    <xsd:element ref="IE304V4Sal:CC304A"/>
                    <xsd:element ref="IE305V4Sal:CC305A"/>
                    <xsd:element ref="IE351V4Sal:CC351A"/>
                    <xsd:element ref="IE917V4Sal:CD917B"/>
                </xsd:choice>
            </xsd:complexType>
            <xsd:element name="Salida" type="IE313V4:IE313V4SalType"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="Entrada">
        <wsdl:part name="IE313V4Ent" element="IE313V4Ent:CC313A" />
    </wsdl:message>
    <wsdl:message name="Salida">
        <wsdl:part name="IE313V4Sal" element="IE313V4:Salida" />
    </wsdl:message>
    <wsdl:portType name="IE313V4">
        <wsdl:operation name="IE313V4">
            <wsdl:input name="Entrada" message="IE313V4:Entrada"/>
            <wsdl:output name="Salida" message="IE313V4:Salida"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="IE313V4SoapBinding" type="IE313V4:IE313V4">
        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IE313V4">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="Entrada">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="Salida">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="IE313V4Service">
        <wsdl:port name="IE313V4" binding="IE313V4:IE313V4SoapBinding">
            <wsdlsoap:address location="https://www1.agenciatributaria.gob.es/L/inwinvoc/es.aeat.dit.adu.aden.enswsv4.IE313V4SOAP"/>
        </wsdl:port>
        <wsdl:port binding="IE313V4:IE313V4SoapBinding" name="IE313V4Pruebas">
            <wsdlsoap:address location="https://www1.agenciatributaria.gob.es/L/inwinvoc/es.aeat.dit.adu.aden.enswsv4.IE313P4SOAP" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
